# Generated by Django 6.0.3 on 2026-05-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('company_create', "Kompaniya qo'shildi"), ('company_update', 'Kompaniya yangilandi'), ('company_delete', "Kompaniya o'chirildi"), ('branch_create', "Filial qo'shildi"), ('branch_update', 'Filial yangilandi'), ('branch_delete', "Filial o'chirildi"), ('branch_payment', "Filialga to'lov qilindi"), ('product_create', "Mahsulot qo'shildi"), ('product_update', 'Mahsulot yangilandi'), ('product_delete', "Mahsulot o'chirildi"), ('stock_add', 'Stock kirim qilindi'), ('stock_adjust', 'Stock tuzatildi'), ('stock_delete', "Batch o'chirildi"), ('stock_return', 'Omborga qaytarish (batch)'), ('sale', 'Sotuv amalga oshirildi'), ('sale_return', 'Sotuv qaytarildi'), ('payment', "To'lov qabul qilindi"), ('payment_refund', "To'lov qaytarildi"), ('client_create', "Mijoz qo'shildi"), ('client_update', 'Mijoz yangilandi'), ('client_delete', "Mijoz o'chirildi")], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faoliyat',
                'verbose_name_plural': 'Faoliyat tarixi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx')],
            },
        ),
    ]
