# Generated by Django 6.0.3 on 2026-06-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitylog_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('company_create', "Kompaniya qo'shildi"), ('company_update', 'Kompaniya yangilandi'), ('company_delete', "Kompaniya o'chirildi"), ('branch_create', "Filial qo'shildi"), ('branch_update', 'Filial yangilandi'), ('branch_delete', "Filial o'chirildi"), ('branch_payment', "Filialga to'lov qilindi"), ('product_create', "Mahsulot qo'shildi"), ('product_update', 'Mahsulot yangilandi'), ('product_delete', "Mahsulot o'chirildi"), ('stock_add', 'Stock kirim qilindi'), ('stock_adjust', 'Stock tuzatildi'), ('stock_delete', "Batch o'chirildi"), ('stock_return', 'Omborga qaytarish (batch)'), ('sale', 'Sotuv amalga oshirildi'), ('sale_return', 'Sotuv qaytarildi'), ('payment', "To'lov qabul qilindi"), ('payment_refund', "To'lov qaytarildi"), ('client_create', "Mijoz qo'shildi"), ('client_update', 'Mijoz yangilandi'), ('client_delete', "Mijoz o'chirildi"), ('container_given', 'Idish berildi'), ('container_returned', 'Idish qaytarildi'), ('container_stock_add', "Idish omborga qo'shildi")], max_length=30),
        ),
    ]
