# Generated by Django 6.0.3 on 2026-06-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, help_text="Foydalanuvchi qaysi biznesga tegishli (aka/uka). Superadmin ham o'z biznesiga ega, lekin boshqalarga 'almashishi' mumkin.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='business.business', verbose_name='Biznes'),
        ),
    ]
