# Generated by Django 6.0.3 on 2026-06-22 19:43
# QO'LDA TUZATILDI: quantity ustunini o'zgartirishdan oldin
# Materialized View larni DROP qilamiz, keyin qaytadan CREATE qilamiz —
# chunki PostgreSQL MV bog'liq ustunni ALTER qilishga ruxsat bermaydi.

from django.db import migrations, models


# ── MV larni vaqtincha o'chirish (field o'zgarishidan OLDIN) ───────────────
DROP_ALL_MVS = """
DROP MATERIALIZED VIEW IF EXISTS dashboard_summary_mv;
DROP MATERIALIZED VIEW IF EXISTS monthly_summary_mv;
DROP MATERIALIZED VIEW IF EXISTS yearly_summary_mv;
DROP MATERIALIZED VIEW IF EXISTS top_products_mv;
"""

# ── MV larni qaytadan yaratish (field o'zgarishidan KEYIN) ─────────────────
# SQL matni notebook/dashboard/migrations/0002_fix_profit_formula.py va
# 0001_create_materialized_views.py dagi bilan AYNAN bir xil — faqat
# endi quantity ustuni numeric(10,3) bo'lgani uchun muammosiz ishlaydi.

RECREATE_DAILY = """
CREATE MATERIALIZED VIEW dashboard_summary_mv AS
WITH sales_data AS (
    SELECT
        DATE(s.created_at) AS date,
        SUM(si.price_at_sale      * (si.quantity - si.returned_quantity)) AS total_sales,
        SUM(si.cost_price_at_sale * (si.quantity - si.returned_quantity)) AS total_expense
    FROM sales_sale s
    JOIN sales_saleitem si ON si.sale_id = s.id
    WHERE s.status = 'active'
    GROUP BY DATE(s.created_at)
),
payments_data AS (
    SELECT
        DATE(p.created_at) AS date,
        SUM(p.amount - p.refunded_amount) AS total_payments
    FROM payments_payment p
    GROUP BY DATE(p.created_at)
)
SELECT
    COALESCE(sd.date, pd.date)                                   AS date,
    COALESCE(sd.total_sales, 0)                                  AS total_sales,
    COALESCE(sd.total_expense, 0)                                AS total_expense,
    COALESCE(pd.total_payments, 0)                               AS total_payments,
    COALESCE(pd.total_payments, 0) - COALESCE(sd.total_expense, 0) AS total_profit,
    COALESCE(sd.total_sales, 0)    - COALESCE(sd.total_expense, 0) AS gross_profit
FROM sales_data sd
FULL OUTER JOIN payments_data pd ON sd.date = pd.date
WITH DATA;
"""

RECREATE_DAILY_INDEX = """
CREATE UNIQUE INDEX dashboard_summary_mv_date_idx
    ON dashboard_summary_mv (date);
"""

RECREATE_MONTHLY = """
CREATE MATERIALIZED VIEW monthly_summary_mv AS
WITH sales_data AS (
    SELECT
        DATE_TRUNC('month', s.created_at)::date AS month,
        SUM(si.price_at_sale      * (si.quantity - si.returned_quantity)) AS total_sales,
        SUM(si.cost_price_at_sale * (si.quantity - si.returned_quantity)) AS total_expense
    FROM sales_sale s
    JOIN sales_saleitem si ON si.sale_id = s.id
    WHERE s.status = 'active'
    GROUP BY DATE_TRUNC('month', s.created_at)
),
payments_data AS (
    SELECT
        DATE_TRUNC('month', p.created_at)::date AS month,
        SUM(p.amount - p.refunded_amount) AS total_payments
    FROM payments_payment p
    GROUP BY DATE_TRUNC('month', p.created_at)
)
SELECT
    COALESCE(sd.month, pd.month)                                  AS month,
    COALESCE(sd.total_sales, 0)                                   AS total_sales,
    COALESCE(sd.total_expense, 0)                                 AS total_expense,
    COALESCE(pd.total_payments, 0)                                AS total_payments,
    COALESCE(pd.total_payments, 0) - COALESCE(sd.total_expense, 0) AS total_profit,
    COALESCE(sd.total_sales, 0)    - COALESCE(sd.total_expense, 0) AS gross_profit
FROM sales_data sd
FULL OUTER JOIN payments_data pd ON sd.month = pd.month
WITH DATA;
"""

RECREATE_MONTHLY_INDEX = """
CREATE UNIQUE INDEX monthly_summary_mv_month_idx
    ON monthly_summary_mv (month);
"""

RECREATE_YEARLY = """
CREATE MATERIALIZED VIEW yearly_summary_mv AS
WITH sales_data AS (
    SELECT
        EXTRACT(YEAR FROM s.created_at)::int AS year,
        SUM(si.price_at_sale      * (si.quantity - si.returned_quantity)) AS total_sales,
        SUM(si.cost_price_at_sale * (si.quantity - si.returned_quantity)) AS total_expense
    FROM sales_sale s
    JOIN sales_saleitem si ON si.sale_id = s.id
    WHERE s.status = 'active'
    GROUP BY EXTRACT(YEAR FROM s.created_at)
),
payments_data AS (
    SELECT
        EXTRACT(YEAR FROM p.created_at)::int AS year,
        SUM(p.amount - p.refunded_amount) AS total_payments
    FROM payments_payment p
    GROUP BY EXTRACT(YEAR FROM p.created_at)
)
SELECT
    COALESCE(sd.year, pd.year)                                    AS year,
    COALESCE(sd.total_sales, 0)                                   AS total_sales,
    COALESCE(sd.total_expense, 0)                                 AS total_expense,
    COALESCE(pd.total_payments, 0)                                AS total_payments,
    COALESCE(pd.total_payments, 0) - COALESCE(sd.total_expense, 0) AS total_profit,
    COALESCE(sd.total_sales, 0)    - COALESCE(sd.total_expense, 0) AS gross_profit
FROM sales_data sd
FULL OUTER JOIN payments_data pd ON sd.year = pd.year
WITH DATA;
"""

RECREATE_YEARLY_INDEX = """
CREATE UNIQUE INDEX yearly_summary_mv_year_idx
    ON yearly_summary_mv (year);
"""

RECREATE_TOP_PRODUCTS = """
CREATE MATERIALIZED VIEW top_products_mv AS
SELECT
    p.id                                            AS product_id,
    p.name                                          AS product_name,
    COALESCE(c.name, 'Kategoriyasiz')               AS category_name,

    COALESCE(
        SUM(si.quantity - si.returned_quantity),
        0
    ) AS total_sold,

    COALESCE(
        SUM(
            (si.quantity - si.returned_quantity)
            * si.price_at_sale
        ),
        0
    ) AS total_revenue,

    COALESCE(
        SUM(
            (si.quantity - si.returned_quantity)
            * (si.price_at_sale - si.cost_price_at_sale)
        ),
        0
    ) AS total_profit

FROM catalog_product p
LEFT JOIN sales_saleitem si ON si.product_id = p.id
LEFT JOIN sales_sale s
    ON s.id = si.sale_id
    AND s.status = 'active'
LEFT JOIN catalog_category c ON c.id = p.category_id

GROUP BY p.id, p.name, c.name
WITH DATA;
"""

RECREATE_TOP_PRODUCTS_INDEX = """
CREATE UNIQUE INDEX top_products_mv_product_id_idx
    ON top_products_mv (product_id);
"""

RECREATE_ALL_MVS = (
    RECREATE_DAILY + RECREATE_DAILY_INDEX +
    RECREATE_MONTHLY + RECREATE_MONTHLY_INDEX +
    RECREATE_YEARLY + RECREATE_YEARLY_INDEX +
    RECREATE_TOP_PRODUCTS + RECREATE_TOP_PRODUCTS_INDEX
)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        ("dashboard", "0002_fix_profit_formula"),  # MV lar shu migrationda yaratilgan
    ]

    operations = [
        # 1) MV larni o'chiramiz — endi quantity ustunini o'zgartirish mumkin
        migrations.RunSQL(
            sql=DROP_ALL_MVS,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 2) Field o'zgarishlari (Django avtomatik generatsiya qilgan)
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(max_digits=10, decimal_places=3),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="returned_quantity",
            field=models.DecimalField(max_digits=10, decimal_places=3, default=0),
        ),
        migrations.AlterField(
            model_name="salereturnitem",
            name="returned_quantity",
            field=models.DecimalField(max_digits=10, decimal_places=3),
        ),

        # 3) MV larni qaytadan yaratamiz — endi numeric quantity bilan ishlaydi
        migrations.RunSQL(
            sql=RECREATE_ALL_MVS,
            reverse_sql=DROP_ALL_MVS,
        ),
    ]