# Generated by Django 6.0.3 on 2026-05-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Qabul qilingan')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='Qoldiq')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tan narxi')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Sotib olingan paytdagi sotuv narxi (snapshot)', max_digits=10, verbose_name='Sotuv narxi (snapshot)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='company.branch', verbose_name='Filial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': "Stock Batch'lar",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Miqdorni oshirish'), ('decrease', 'Miqdorni kamaytirish'), ('price_change', "Narxni o'zgartirish"), ('correction', "To'liq tuzatish"), ('return', 'Sotuv qaytarish')], max_length=20)),
                ('quantity_change', models.IntegerField(blank=True, null=True)),
                ('new_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.stockbatch')),
            ],
            options={
                'verbose_name': 'Stock tuzatish',
                'verbose_name_plural': 'Stock tuzatishlar',
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_1784db_idx'),
        ),
    ]
