# Generated by Django 6.0.3 on 2026-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='box_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Necha karobka sotib olingan (agar karobkalab olingan bo'lsa)", null=True, verbose_name='Karobka soni'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='units_per_box',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="1 karobkada nechta dona/kg bo'lgan", max_digits=10, null=True, verbose_name='1 karobkadagi miqdor'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='1 birlik (dona/kg) tan narxi', max_digits=10, verbose_name='Tan narxi'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qabul qilingan'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qoldiq'),
        ),
    ]
