# Generated by Django 6.0.3 on 2026-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Yaratishda kiritilgan tan narxi — Sotib olish modalida default sifatida ko'rsatiladi", max_digits=10, verbose_name='Standart tan narxi'),
        ),
    ]
