# Generated by Django 6.0.3 on 2026-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_default_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogram')], default='dona', help_text='Mahsulot dona yoki kilogramda sotiladimi', max_length=10, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Dona yoki kg (unit_type ga qarab)', max_digits=10, verbose_name='Qoldiq'),
        ),
    ]
