# Generated by Django 6.0.3 on 2026-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_unit_type_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_box_enabled',
            field=models.BooleanField(default=False, help_text="Yoqilsa, xarid va sotuvda 'Karobkalab' rejimi ham ko'rinadi", verbose_name='Karobkalab sotiladi/olinadi'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="1 karobkada nechta dona/kg bo'ladi (doimiy, mahsulot uchun bir marta belgilanadi)", max_digits=10, null=True, verbose_name='1 karobkadagi miqdor'),
        ),
    ]
