# Generated by Django 6.0.3 on 2026-06-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_backfill_default_business'),
        ('catalog', '0004_product_is_box_enabled_product_units_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business.business', verbose_name='Biznes'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business', verbose_name='Biznes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'slug')},
        ),
    ]
