# Generated by Django 6.0.3 on 2026-06-23 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_add_location_fields'),
        ('company', '0002_add_advance_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idish turi',
                'verbose_name_plural': 'Idish turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('given', 'Berildi'), ('returned', 'Qaytarildi')], max_length=10, verbose_name='Amal')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_transactions', to='company.branch', verbose_name='Filial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_transactions', to='clients.client', verbose_name='Mijoz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_transactions', to=settings.AUTH_USER_MODEL)),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='containers.containertype', verbose_name='Idish turi')),
            ],
            options={
                'verbose_name': 'Idish tranzaksiyasi',
                'verbose_name_plural': 'Idish tranzaksiyalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='containers__client__791aed_idx'), models.Index(fields=['branch', 'created_at'], name='containers__branch__96a816_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Mijozda bor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='clients.client', verbose_name='Mijoz')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_holdings', to='containers.containertype', verbose_name='Idish turi')),
            ],
            options={
                'verbose_name': 'Mijozdagi idish',
                'verbose_name_plural': 'Mijozlardagi idishlar',
                'unique_together': {('client', 'container_type')},
            },
        ),
        migrations.CreateModel(
            name='BranchContainerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Omborda qoldi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_stocks', to='company.branch', verbose_name='Filial')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stocks', to='containers.containertype', verbose_name='Idish turi')),
            ],
            options={
                'verbose_name': 'Filial idish ombori',
                'verbose_name_plural': 'Filial idish omborlari',
                'unique_together': {('branch', 'container_type')},
            },
        ),
    ]
