# Generated by Django 6.0.3 on 2026-06-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_backfill_more_models'),
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_types', to='business.business', verbose_name='Biznes'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='containertype',
            unique_together={('business', 'name')},
        ),
    ]
