# Generated by Django 6.0.3 on 2026-06-24 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_backfill_more_models'),
        ('clients', '0003_client_business_region_business_alter_region_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Matn')),
                ('status', models.CharField(choices=[('pending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], default='pending', max_length=10)),
                ('eskiz_id', models.CharField(blank=True, max_length=64, verbose_name='Eskiz ID')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='business.business', verbose_name='Biznes')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='clients.client', verbose_name='Mijoz')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS tarixi',
                'verbose_name_plural': 'SMS tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
