# Generated by Django 6.0.3 on 2026-05-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filial nomi')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bizning qarzimiz (filialga)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('transfer', "O'tkazma"), ('discount', 'Chegirma')], default='cash', max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.branch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Filialga to'lov",
                'verbose_name_plural': "Filialga to'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bizning qarzimiz')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company'),
        ),
    ]
