# Generated by Django 6.0.3 on 2026-06-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_backfill_default_business'),
        ('company', '0002_add_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='business.business', verbose_name='Biznes'),
        ),
    ]
