# Generated by Django 6.0.3 on 2026-06-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('clients', '0002_add_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='business.business', verbose_name='Biznes'),
        ),
        migrations.AddField(
            model_name='region',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='business.business', verbose_name='Biznes'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('business', 'name')},
        ),
    ]
