# Generated by Django 6.0.3 on 2026-06-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_business_webhook_token'),
        ('clients', '0003_client_business_region_business_alter_region_name_and_more'),
        ('payments', '0002_payment_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Asl matn (SMS/bildirishnoma)')),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Aniqlangan summa (taxminiy)')),
                ('sender_hint', models.CharField(blank=True, max_length=120, verbose_name="Jo'natuvchi (agar bor bo'lsa)")),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('notification', 'Bildirishnoma'), ('manual', "Qo'lda kiritilgan")], default='sms', max_length=20)),
                ('status', models.CharField(choices=[('unmatched', 'Kutmoqda'), ('matched', 'Bogʼlandi'), ('ignored', 'Eʼtibor berilmadi')], default='unmatched', max_length=12)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='business.business', verbose_name='Biznes')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='clients.client', verbose_name="Bog'langan mijoz")),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transaction', to='payments.payment', verbose_name="Yaratilgan to'lov")),
            ],
            options={
                'verbose_name': "Kelgan to'lov (tasdiqlanmagan)",
                'verbose_name_plural': "Kelgan to'lovlar (tasdiqlanmagan)",
                'ordering': ['-created_at'],
            },
        ),
    ]
